### ISSUE TITLE
Crash on Startup (Incompatible with FerriteCore?)

### ISSUE THREAD

**Issue by pewblaze** [MerchantPug/die-your-way#1]
The Game crashes on Startup when i have FerriteCore installed.
Without your mod everythings fine. 
I also started the game without FerriteCore, it doesnt crash.

I didn't add any files yet for the Death Messages.

Heres the Crashlog with FerriteCore:
[crash-2022-01-11_17.05.15-client.txt](https://github.com/MerchantPug/die-your-way/files/7848093/crash-2022-01-11_17.05.15-client.txt)

**Comment by ChrysanthCow** [comment]
Have you tried starting the game again? I'm unsure if my mod is the one causing crashes as I don't touch client exclusive code like the crash there does.

**Comment by MerchantPug** [comment]
I'm able to launch fine, just tested now.

**Comment by ChrysanthCow** [comment]
You've probably got an outdated version of FerriteCore. (You need 4.0.0)

The automatic download being the 1.16 version got me too.

**Comment by ChrysanthCow** [comment]
Closed #1.

@pewblaze was using an outdated version of FerriteCore.
